const assert=require('node:assert/strict'),path=require('node:path'),os=require('node:os');
const {mkdtemp,readFile,writeFile,rm,mkdir,symlink}=require('node:fs/promises');
const {app,BrowserWindow,session,clipboard,shell,dialog,WebContentsView,ipcMain}=require('electron');
const appRoot=process.env.FABLES_TEST_APP_ROOT||path.join(__dirname, '..', '..');
const {registerAppearanceScheme}=require(path.join(appRoot,'dist/appearance/appearance'));
const {MusicManager,MUSIC_URL}=require(path.join(appRoot,'dist/music/music'));
const {DEFAULT_APPEARANCE}=require(path.join(appRoot,'dist/appearance/themes'));
const {MUSIC_CATALOG}=require(path.join(appRoot,'dist/music/music-catalog'));
registerAppearanceScheme();app.on('window-all-closed',()=>{});
// Prevent Electron's default fatal-error dialog from hiding teardown failures.
for(const event of ['uncaughtException','unhandledRejection'])process.on(event,error=>{console.error(`Music smoke ${event}:`,error);app.exit(1)});
const timer=setTimeout(()=>{console.error('Music test timed out.');app.exit(1)},50000);
let profile,parent,player,forged,manager,toolbar;
let copied;
const externalLinks=[];shell.openExternal=async url=>{externalLinks.push(url)};
const writeClipboard=clipboard.writeText.bind(clipboard);
clipboard.writeText=value=>{copied=value;writeClipboard(value)};
const sleep=ms=>new Promise(resolve=>setTimeout(resolve,ms));
const wav=Buffer.alloc(44+8000*2*8);
wav.write('RIFF',0);wav.writeUInt32LE(wav.length-8,4);wav.write('WAVEfmt ',8);wav.writeUInt32LE(16,16);wav.writeUInt16LE(1,20);wav.writeUInt16LE(1,22);wav.writeUInt32LE(8000,24);wav.writeUInt32LE(16000,28);wav.writeUInt16LE(2,32);wav.writeUInt16LE(16,34);wav.write('data',36);wav.writeUInt32LE(wav.length-44,40);
const html=`<!doctype html><html><body><div class="grid relative" id="composer"><div id="working-context-bar-spacer"></div><div class="tiptap" contenteditable="true">Draft unchanged</div><button aria-label="Roll dice" id="dice">Dice</button></div><form><button aria-label="Roll dice">Form dice</button></form><div role="dialog"><button aria-label="Roll dice">Dialog dice</button></div></body></html>`;
(async()=>{
 profile=process.env.FABLES_TEST_PROFILE_DIR||await mkdtemp(path.join(os.tmpdir(),'fables-music-test-'));app.setPath('userData',profile);await app.whenReady();
 manager=new MusicManager();await manager.initialize();
 let requests=0;const requestUrls=[];
 session.fromPartition('fables-music').protocol.handle('https',request=>{
  requests++;requestUrls.push(request.url);const range=/bytes=(\d+)-(\d*)/.exec(request.headers.get('range')||'');
  if(new URL(request.url).pathname==='/broken.wav')return new Response('Missing',{status:404});
  const start=range?Number(range[1]):0,end=range&&range[2]?Math.min(Number(range[2]),wav.length-1):wav.length-1;
  return new Response(wav.subarray(start,end+1),{status:range?206:200,headers:{'Content-Type':'audio/wav','Accept-Ranges':'bytes','Content-Length':String(end-start+1),...(range?{'Content-Range':`bytes ${start}-${end}/${wav.length}`}:{})}});
 });
 const website=session.fromPartition('music-test-site');website.protocol.handle('https',()=>new Response(html,{headers:{'Content-Type':'text/html'}}));
 parent=new BrowserWindow({show:false,width:1000,height:800,webPreferences:{session:website,sandbox:true,contextIsolation:true,nodeIntegration:false}});
 manager.attach(parent.webContents);let opened=0;
 parent.webContents.setWindowOpenHandler(({url})=>{if(manager.handleOpenRequest(parent.webContents,parent,url))opened++;return {action:'deny'}});
 await parent.loadURL('https://play.fables.gg/campaign/play');
 const siteJs=source=>parent.webContents.executeJavaScript(source);
 const until=async predicate=>{for(let i=0;i<250;i++){if(await predicate())return;await sleep(20)}throw Error('Timed out waiting for music state')};
 await until(()=>siteJs("!!document.querySelector('[data-ff-desktop-music-button]')"));
 assert.equal(await siteJs("document.querySelectorAll('[data-ff-desktop-music-button]').length"),1);
 assert.equal(await siteJs('typeof window.music'),'undefined');assert.equal(await siteJs('typeof window.require'),'undefined');
 assert.equal(await siteJs("document.getElementById('dice').nextElementSibling.hasAttribute('data-ff-desktop-music-button')"),true);
 await siteJs("document.querySelector('[data-ff-desktop-music-button]').click()");await until(()=>opened===1);
 player=await manager.open(parent);manager.hide();const js=source=>player.webContents.executeJavaScript(source);
 await until(()=>js("!document.getElementById('title').disabled"));
 const saved=()=>readFile(path.join(profile,'music.json'),'utf8').then(JSON.parse).catch(()=>null);
 const add=async(title,url)=>js(`document.getElementById('title').value=${JSON.stringify(title)};document.getElementById('url').value=${JSON.stringify(url)};document.getElementById('add-track').dispatchEvent(new Event('submit',{bubbles:true,cancelable:true}))`);
 await add('<img src=x onerror=alert(1)>','https://audio.fixture/first.wav');await until(async()=>(await saved())?.tracks.length===1);
 assert.equal(await js("document.querySelector('#playlist img')"),null);
 assert.equal(requests,0,'Saved tracks do not contact audio hosts until Play.');
 await add('Second track','https://audio.fixture/second.wav');await until(async()=>(await saved())?.tracks.length===2);
 await js("document.getElementById('play').click()");await until(()=>js("!document.getElementById('audio').paused && Number.isFinite(document.getElementById('audio').duration)"));
 assert(requests>0);assert.equal(await js("document.getElementById('audio').duration"),8);
 await js("document.getElementById('volume').value=23;document.getElementById('volume').dispatchEvent(new Event('input'));document.getElementById('volume').dispatchEvent(new Event('change'));document.getElementById('mute').click();document.getElementById('loop').click()");
 await until(async()=>{const state=await saved();return state?.volume===.23&&state.muted&&state.loop});
 assert.equal(await js("document.getElementById('audio').volume"),.23);assert.equal(await js("document.getElementById('audio').muted"),true);assert.equal(await js("document.getElementById('audio').loop"),true);
 await js("document.getElementById('seek').value=500;document.getElementById('seek').dispatchEvent(new Event('input'))");
 assert((await js("document.getElementById('audio').currentTime"))>=4);
 await js("document.getElementById('play').click()");assert.equal(await js("document.getElementById('audio').paused"),true);
 await js("document.getElementById('next').click()");await until(async()=>(await saved())?.selected===(await saved())?.tracks[1].id);
 assert.equal(await js("document.getElementById('audio').paused"),true,'Skipping while paused does not start playback.');
 await js("document.getElementById('loop').click();document.querySelector('#playlist .track').click()");
 await until(()=>js("!document.getElementById('audio').paused && Number.isFinite(document.getElementById('audio').duration)"));
 await js("document.getElementById('audio').currentTime=7.95");
 await until(()=>js("document.getElementById('audio').getAttribute('src')==='https://audio.fixture/second.wav' && !document.getElementById('audio').paused"));
 await js("document.getElementById('play').click();document.getElementById('loop').click()");
 await manager.open(parent);parent.show();player.webContents.focus();await sleep(100);
 await js("document.getElementById('copy').click()");await until(()=>js("document.getElementById('save-status').textContent==='Track link copied.'"));
 assert.equal(copied,'https://audio.fixture/second.wav','The trusted handler passes only the saved URL to the system clipboard.');
 if(process.platform!=='linux'||!process.env.WAYLAND_DISPLAY)assert.equal(await clipboard.readText(),copied);
 manager.setInterface({...DEFAULT_APPEARANCE,preset:'light'},'ru');
 await until(()=>js("document.documentElement.lang==='ru'"));assert.equal(await js("document.getElementById('mute').textContent"),'Включить звук');assert.equal(await js("document.documentElement.style.getPropertyValue('--ui-bg')"),'#f5f5f5');
 await until(()=>siteJs("document.querySelector('[data-ff-desktop-music-button]').title==='Музыкальный проигрыватель'"));
 await add('Page link','https://www.youtube.com/watch?v=test');assert.equal(await js("document.getElementById('save-status').textContent"),'Это ссылка на веб-страницу. Укажите прямую ссылку на аудиофайл.');
 assert.equal((await saved()).tracks.length,2);
 forged=new BrowserWindow({show:false,webPreferences:{partition:'fables-music',preload:path.join(appRoot,'dist/music/music-preload.js'),sandbox:true,contextIsolation:true,nodeIntegration:false}});
 await forged.loadURL(MUSIC_URL);
 assert.match(await forged.webContents.executeJavaScript("window.music.get().then(()=> 'allowed',error=>error.message)"),/only in the app player/);
 assert.match(await forged.webContents.executeJavaScript("window.music.save({}).then(()=> 'allowed',error=>error.message)"),/only in the app player/);
 assert.match(await forged.webContents.executeJavaScript("window.music.copyAttribution('scott-titan').then(()=> 'allowed',error=>error.message)"),/only in the app player/);
 assert.match(await forged.webContents.executeJavaScript("window.music.openCatalogLink('scott-titan','source').then(()=> 'allowed',error=>error.message)"),/only in the app player/);
 forged.destroy();forged=null;
 assert.equal(manager.handleOpenRequest(parent.webContents,parent,MUSIC_URL+'other'),false);
 await siteJs("history.pushState({},'', '/campaign/play?view=world');document.body.append(document.createElement('div'))");await until(()=>siteJs("!document.querySelector('[data-ff-desktop-music-button]')"));
 await siteJs("history.pushState({},'', '/campaign/play');document.body.append(document.createElement('div'))");await until(()=>siteJs("!!document.querySelector('[data-ff-desktop-music-button]')"));
 assert.equal(await siteJs("document.querySelector('.tiptap').textContent"),'Draft unchanged');
 await js("document.getElementById('play').click()");await until(()=>js("!document.getElementById('audio').paused && document.getElementById('audio').currentTime>0"));
 const beforeReload=requests;parent.webContents.reload();await sleep(150);assert.equal(requests,beforeReload,'Website reload does not restart the player.');
 assert.equal(await js("document.getElementById('audio').paused"),false);
 const timeBeforeHide=await js("document.getElementById('audio').currentTime");await js("document.getElementById('close-library').click()");await sleep(200);assert.equal(player.getVisible(),false);assert.equal(await js("document.getElementById('audio').paused"),false,'Closing library keeps playback running.');assert((await js("document.getElementById('audio').currentTime"))>timeBeforeHide);await manager.open(parent);
 await js("document.getElementById('stop').click()");assert.equal(await js("document.getElementById('audio').hasAttribute('src')"),false);
 await js("document.getElementById('title').value='Tavern ambience';document.getElementById('url').value='https://audio.fixture/tavern.ogg'");
 if(process.env.FABLES_MUSIC_SCREENSHOT)await writeFile(process.env.FABLES_MUSIC_SCREENSHOT,(await player.webContents.capturePage()).toPNG());
 const previousPlayer=player;manager.hide();player=await manager.open(parent);assert.equal(player,previousPlayer,'Closing the library retains its audio renderer.');manager.hide();const reopened=source=>player.webContents.executeJavaScript(source);await until(()=>reopened("!document.getElementById('title').disabled"));
 assert.equal(await reopened("document.querySelectorAll('#playlist li').length"),2);assert.equal(await reopened("document.getElementById('volume').value"),'23');assert.equal(await reopened("document.getElementById('audio').paused"),true);
 assert.equal(await reopened("document.getElementById('audio').hasAttribute('src')"),false,'Reopening never autoplays a saved track.');
 await reopened("document.querySelector('#playlist li[aria-current=true] .remove').click()");await until(async()=>(await saved())?.tracks.length===1);
 assert.equal(await reopened("document.querySelector('#playlist li[aria-current=true] .track').textContent.includes('<img')"),true);
 const final=await saved();await manager.shutdown();player=null;
 manager=new MusicManager();await manager.initialize();assert.deepEqual(manager.getSettings(),final,'Playlist and playback preferences survive restarting the manager.');
 const requestsBeforeRestart=requests;player=await manager.open(parent);manager.hide();await until(()=>reopened("!document.getElementById('title').disabled"));
 assert.equal(requests,requestsBeforeRestart);assert.equal(await reopened("document.getElementById('audio').paused"),true);
 await add('Broken link','https://audio.fixture/broken.wav');await until(async()=>(await saved())?.tracks.length===2);
 await reopened("document.querySelector('#playlist li:last-child .track').click()");
 await until(()=>reopened("document.getElementById('playback-status').classList.contains('error')"));
 assert.equal(await reopened("document.getElementById('audio').paused"),true);
 assert.equal(await reopened("document.querySelector('.player #play').disabled"),false,'An unavailable audio link leaves playback controls usable.');
 const requestsBeforeCatalog=requests;
 await reopened("document.getElementById('catalog-tab').click()");assert.equal(await reopened("document.getElementById('playlist-panel').hidden"),true);assert.equal(await reopened("document.getElementById('catalog-panel').hidden"),false);
 const search=async value=>reopened(`document.getElementById('catalog-search').value=${JSON.stringify(value)};document.getElementById('catalog-search').dispatchEvent(new Event('input'))`);
 assert.equal(await reopened("document.querySelectorAll('#catalog li').length"),12);
 await reopened("document.getElementById('catalog-more').click()");assert.equal(await reopened("document.querySelectorAll('#catalog li').length"),24,'Catalog rendering is paginated.');
 await search('zz-no-such-track');assert.equal(await reopened("document.getElementById('catalog-empty').hidden"),false);
 await search('виолончель');assert((await reopened("document.querySelectorAll('#catalog li').length"))>0,'Russian instrument names are searchable.');
 await search('battle');assert((await reopened("document.querySelectorAll('#catalog li').length"))>0,'Scene keywords are searchable.');
 await search('');await reopened("document.getElementById('catalog-mood').value='militaristic';document.getElementById('catalog-genre').value='orchestral';document.getElementById('catalog-mood').dispatchEvent(new Event('change'))");
 const filtered=await reopened("[...document.querySelectorAll('#catalog li')].map(row=>row.dataset.catalogId)");assert(filtered.length>0);assert(filtered.every(id=>MUSIC_CATALOG.find(track=>track.id===id).moods.includes('militaristic')));assert(filtered.every(id=>MUSIC_CATALOG.find(track=>track.id===id).genres.includes('orchestral')));
 await reopened("document.getElementById('catalog-mood').value='';document.getElementById('catalog-genre').value=''");await search('TiTaN');
 assert.equal(await reopened("document.querySelectorAll('#catalog li').length"),1);assert.equal(await reopened("document.querySelector('#catalog h3').textContent"),'Titan');
 assert.equal(requests,requestsBeforeCatalog,'Browsing and searching the whole catalog makes no audio request.');
 await reopened("document.querySelector('#catalog [data-action=add]').click();document.querySelector('#catalog [data-action=add]').click()");await until(async()=>(await saved())?.tracks.length===3);
 assert.equal(requests,requestsBeforeCatalog,'Adding a catalog track never autoplays.');assert.equal((await saved()).tracks.filter(track=>track.url===MUSIC_CATALOG.find(track=>track.id==='scott-titan').url).length,1);
 await until(()=>reopened("!document.querySelector('#catalog [data-action=play]').disabled"));await reopened("{const a=document.getElementById('audio'),play=a.play.bind(a);a.play=async()=>{try{return await play()}catch(error){window.fixturePlayError={name:error.name,message:error.message};throw error}}}document.querySelector('#catalog [data-action=play]').click()");
 try{await until(()=>reopened("!document.getElementById('audio').paused && Number.isFinite(document.getElementById('audio').duration)"));}catch(error){console.error('Catalog playback diagnostic',requestUrls.slice(-4),await reopened("(()=>{const a=document.getElementById('audio');return {src:a.getAttribute('src'),paused:a.paused,duration:a.duration,error:a.error?.message,playError:window.fixturePlayError,status:document.getElementById('playback-status').textContent,title:document.getElementById('track-title').textContent}})()"));throw error;}
 assert.equal((await saved()).tracks.length,3,'Playing an added track reuses it.');assert.equal(await reopened("document.getElementById('track-credit').hidden"),false);
 await reopened("document.getElementById('copy-credit').click()");await until(()=>reopened("document.getElementById('save-status').textContent==='Attribution copied.'"));assert.match(copied,/Titan by Scott Buckley/);assert.match(copied,/creativecommons.org\/licenses\/by\/4.0/);
 await reopened("document.querySelector('#catalog [data-action=source]').click();document.querySelector('#catalog [data-action=license]').click()");await until(()=>externalLinks.length===2);
 assert.deepEqual(externalLinks,['https://www.scottbuckley.com.au/library/titan/','https://creativecommons.org/licenses/by/4.0/']);
 await assert.rejects(reopened("window.music.openCatalogLink('scott-titan','https://example.com')"),/Unknown catalog link/);
 manager.setInterface({...DEFAULT_APPEARANCE,preset:'light'},'ru');await until(()=>reopened("document.documentElement.lang==='ru'"));
 assert.equal(await reopened("document.getElementById('catalog-heading').textContent"),'Каталог музыки');assert.equal(await reopened("document.getElementById('catalog-search').value"),'TiTaN','Language changes preserve the search.');assert.equal(await reopened("document.getElementById('catalog-mood').firstChild.textContent"),'Все настроения');
 parent.setContentSize(740,880);await sleep(80);assert.equal(await reopened('document.documentElement.scrollWidth<=innerWidth'),true,'Catalog rows fit the minimum window width.');
 if(process.env.FABLES_MUSIC_SCREENSHOT){await manager.open(parent);await reopened("document.getElementById('catalog-heading').scrollIntoView();new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)))");await writeFile(process.env.FABLES_MUSIC_SCREENSHOT.replace(/\.png$/,'-catalog.png'),(await player.webContents.capturePage()).toPNG());}


 manager.hide();
 const owned=session.fromPartition('fables-appearance');owned.protocol.handle('fables-desktop',async request=>{const url=new URL(request.url),name=url.pathname.slice(1);if(url.host!=='settings'||!['appearance-button.html','appearance-button.css','appearance-button.js','settings-theme.js'].includes(name))return new Response('Not found',{status:404});return new Response(await readFile(path.join(appRoot,'assets',name==='settings-theme.js'?'shared':'shell',name)),{headers:{'Content-Type':name.endsWith('.html')?'text/html':name.endsWith('.css')?'text/css':'text/javascript'}});});
 ipcMain.handle('appearance-dock:get',()=>({settings:DEFAULT_APPEARANCE,locale:'en',open:false}));ipcMain.handle('appearance-dock:popup',()=>{});ipcMain.handle('appearance-dock:toggle',()=>{});
 toolbar=new WebContentsView({webPreferences:{partition:'fables-appearance',preload:path.join(appRoot,'dist/shell/appearance-button-preload.js'),sandbox:true,contextIsolation:true,nodeIntegration:false}});parent.contentView.addChildView(toolbar);toolbar.setBounds({x:0,y:0,width:232,height:166});
 manager.attachMain(parent,toolbar.webContents,parent.webContents);await toolbar.webContents.loadURL('fables-desktop://settings/appearance-button.html');const control=source=>toolbar.webContents.executeJavaScript(source);
 await until(()=>control("!document.getElementById('play').disabled"));await control("document.getElementById('stop').click()");await until(()=>reopened("!document.getElementById('audio').hasAttribute('src')"));
 await control("document.getElementById('play').click()");await until(()=>reopened("!document.getElementById('audio').paused"));
 await control("document.getElementById('repeat').click();document.getElementById('volume').value=37;document.getElementById('volume').dispatchEvent(new Event('input'))");await until(()=>reopened("document.getElementById('audio').volume===.37"));assert.equal(await control("document.getElementById('volume-value').value"),'37%');
 if(process.env.FABLES_MUSIC_SCREENSHOT){await control("document.getElementById('volume-button').click();new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)))");await writeFile(process.env.FABLES_MUSIC_SCREENSHOT.replace(/\.png$/,'-toolbar.png'),(await toolbar.webContents.capturePage()).toPNG());await control("document.getElementById('volume-button').click()");}
 const initialTitle=await reopened("document.getElementById('track-title').textContent");await control("document.getElementById('next').click()");await until(async()=>(await reopened("document.getElementById('track-title').textContent"))!==initialTitle);
 await control("document.getElementById('library').click()");await until(()=>player.getVisible());await control("document.getElementById('library').click()");await until(()=>!player.getVisible());assert.equal(await reopened("document.getElementById('audio').paused"),false);
 await assert.rejects(control("window.appearanceButton.control('volume',2)"),/Invalid volume/);await assert.rejects(control("window.appearanceButton.control('filesystem')"),/Invalid music control/);
 const toolbarForgery=new BrowserWindow({show:false,webPreferences:{partition:'fables-appearance',preload:path.join(appRoot,'dist/shell/appearance-button-preload.js'),sandbox:true,contextIsolation:true,nodeIntegration:false}});await toolbarForgery.loadURL('fables-desktop://settings/appearance-button.html');await assert.rejects(toolbarForgery.webContents.executeJavaScript("window.appearanceButton.control('play')"),/only in the app toolbar/);toolbarForgery.destroy();
 await control("document.getElementById('stop').click()");
 const folder=path.join(profile,'downloaded-music'),outside=path.join(profile,'private.wav');await mkdir(path.join(folder,'nested'),{recursive:true});await writeFile(path.join(folder,'Tavern.wav'),wav);await writeFile(path.join(folder,'nested','Battle.wav'),wav);await writeFile(outside,wav);await writeFile(path.join(folder,'notes.txt'),'not audio');
 if(process.platform!=='win32')await symlink(outside,path.join(folder,'escape.wav'));
 dialog.showOpenDialog=async()=>({canceled:false,filePaths:[folder]});
 await reopened("document.getElementById('folders-tab').click();document.getElementById('choose-folder').click()");await until(()=>reopened("document.querySelectorAll('#local-tracks li').length===2"));
 await reopened("document.getElementById('choose-folder').click()");await until(()=>reopened("!document.getElementById('choose-folder').disabled"));
 const library=await reopened("window.music.get().then(state=>state.library)");assert.equal(library.folders.length,1,'Choosing the same source twice does not duplicate folders.');assert.equal(library.tracks.length,2);assert(!JSON.stringify(library).includes(folder),'Renderer receives names and virtual links, never chosen filesystem paths.');
 if(process.env.FABLES_MUSIC_SCREENSHOT){await manager.open(parent);await reopened("document.getElementById('folders-panel').scrollIntoView();new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)))");await writeFile(process.env.FABLES_MUSIC_SCREENSHOT.replace(/\.png$/,'-folders.png'),(await player.webContents.capturePage()).toPNG());}
 const tavern=library.tracks.find(track=>track.title==='Tavern');assert.match(tavern.url,/^fables-desktop:\/\/music\/audio\/[a-f0-9]{64}$/);
 await reopened("document.getElementById('local-search').value='Battle';document.getElementById('local-search').dispatchEvent(new Event('input'))");assert.equal(await reopened("document.querySelectorAll('#local-tracks li').length"),1);
 await reopened("document.getElementById('local-search').value='Tavern';document.getElementById('local-search').dispatchEvent(new Event('input'));document.querySelector('#local-tracks [data-action=play]').click()");await until(()=>reopened("!document.getElementById('audio').paused && Number.isFinite(document.getElementById('audio').duration)"));assert.equal(await reopened("document.getElementById('audio').duration"),8);
 await assert.rejects(reopened(`window.music.save({...${JSON.stringify(manager.getSettings())},tracks:[{id:'unknown',title:'Unknown',url:'fables-desktop://music/audio/${'f'.repeat(64)}'}],selected:'unknown'})`),/Unknown local audio track/);
 const unauthorized=await session.fromPartition('fables-music').fetch('fables-desktop://music/audio/'+ 'f'.repeat(64));assert.equal(unauthorized.status,404);
 if(process.platform!=='win32') {await rm(path.join(folder,'Tavern.wav'));await symlink(outside,path.join(folder,'Tavern.wav'));const escaped=await session.fromPartition('fables-music').fetch(tavern.url);assert.equal(escaped.status,404,'Replacing a scanned audio file with a symlink cannot expose files outside its chosen folder.');}
 await reopened("document.getElementById('stop').click();document.querySelector('#folders button').click()");await until(()=>reopened("document.querySelectorAll('#folders li').length===0"));assert.equal((await readFile(outside)).length,wav.length,'Removing a source never deletes music files.');
 const removed=await session.fromPartition('fables-music').fetch(tavern.url);assert.equal(removed.status,404);
 const playbackContents=player.webContents;parent.destroy();parent=null;await until(()=>playbackContents.isDestroyed());await manager.shutdown();
 console.log('Music smoke passed: persistent embedded audio, toolbar controls, local folder playback/search/removal and path boundaries, real audio, volume/mute/loop/seek, catalog search/filter/pagination, duplicate-free playlist actions, official source/license links, attribution copy, persistence, Russian/themes, composer placement, and restricted IPC.');
 assert.equal(manager.getSettings().tracks.length,4);
} )().then(()=>finish(0),async error=>{console.error(error);await finish(1)});
async function finish(code){clearTimeout(timer);const toolbarContents=toolbar?.webContents;if(toolbarContents&&!toolbarContents.isDestroyed())toolbarContents.close();for(const window of [forged,parent])if(window&&!window.isDestroyed())window.destroy();if(manager)await manager.shutdown();if(profile&&!process.env.FABLES_TEST_PROFILE_DIR)await rm(profile,{recursive:true,force:true,maxRetries:10,retryDelay:100});app.exit(code)}
