// Fixed, shared UI copy. These entries are deliberately separate from prose:
// words such as "Head" and "Voice" must not rewrite campaign narration.
export const SHARED_INTERFACE_GLOSSARY: Record<string, string> = {
  'franz':'Франц', 'details':'Сведения', 'race':'Раса', 'class':'Класс', 'subclass':'Подкласс',
  'alignment':'Мировоззрение', 'pronouns':'Местоимения', 'voice':'Голос', 'faction':'Фракция', 'none':'Нет',
  'backstory':'Предыстория', 'mannerisms':'Манеры', 'carrying capacity':'Грузоподъёмность',
  'currencies':'Валюты', 'currency':'Валюта', 'currency unit':'Единица валюты',
  'gold pieces':'Золотые монеты', 'silver pieces':'Серебряные монеты', 'copper pieces':'Медные монеты',
  'electrum pieces':'Электрумовые монеты', 'platinum pieces':'Платиновые монеты',
  'equipped items':'Надетые предметы', 'armor':'Доспехи', 'head':'Голова', 'neck':'Шея', 'back':'Назад',
  'gloves':'Перчатки', 'belt':'Пояс', 'ring':'Кольцо', 'legs':'Ноги', 'feet':'Ступни',
  'left hand':'Левая рука', 'right hand':'Правая рука', 'view full inventory':'Открыть полный инвентарь',
  'open spellbook':'Открыть книгу заклинаний', 'proficiency':'Умение', 'proficient':'Есть умение',
  'not proficient':'Нет умения', 'expertise':'Компетентность', 'xp until level':'опыта до уровня',
  'hit dice available':'Доступно костей хитов', 'hit die available':'Доступна кость хитов',
  'maximum hp':'Максимум ОЗ', 'current hp':'Текущие ОЗ', 'hp updated':'ОЗ обновлены',
  'exp':'Опыт', 'xp updated':'Опыт обновлён', 'xp update undone':'Изменение опыта отменено',
  'ability scores':'Значения характеристик', 'ability modifier':'Модификатор характеристики', 'ability mod':'Модификатор характеристики',
  'core stats':'Основные характеристики', 'base ac':'Базовый КБ', 'ac modifiers':'Модификаторы КБ',
  'armor class (ac)':'Класс брони (КБ)', 'constitution modifier':'Модификатор Телосложения',
  'wisdom modifier':'Модификатор Мудрости', 'strength requirement':'Требование к Силе',
  'strength modifier':'Модификатор Силы', 'intelligence modifier':'Модификатор Интеллекта',
  'charisma modifier':'Модификатор Харизмы',
  'strength requirement (optional)':'Требование к Силе (необязательно)', 'death saves':'Спасброски от смерти',
  'damage and condition modifiers':'Модификаторы урона и состояний', 'defenses':'Защита',
  'damage type':'Тип урона', 'damage roll':'Бросок урона', 'damage rolls':'Броски урона',
  'damage properties':'Свойства урона', 'damage traits':'Особенности урона', 'vulnerabilities':'Уязвимости',
  'damage on failed save':'Урон при провале спасброска', 'damage on successful save':'Урон при успехе спасброска',
  'attack':'Атака', 'attacks':'Атаки', 'attack details':'Параметры атаки', 'attack type':'Тип атаки',
  'melee attack':'Атака в ближнем бою', 'ranged attack':'Атака в дальнем бою',
  'other':'Другое', 'flee':'Отступление', 'heal':'Лечение', 'critical success':'Критический успех',
  'base roll':'Базовый бросок', 'base damage':'Базовый урон',
  'hp healed':'ОЗ восстановлено', 'hp recovered':'ОЗ восстановлено',
  'cantrip used - no spell slot consumed':'Использован заговор — ячейка заклинания не потрачена',
  'spell slot consumed':'Ячейка заклинания использована', 'spell slot restored':'Ячейка заклинания восстановлена',
  'attack roll required':'Требуется бросок атаки', 'to hit':'Бонус атаки', 'actions':'Действия',
  'action name':'Название действия', 'action description':'Описание действия',
  'weapon':'Оружие', 'weapons':'Оружие', 'weapon properties':'Свойства оружия', 'weapon traits':'Особенности оружия',
  'armor properties':'Свойства доспехов', 'two handed':'Двуручное', 'two-handed damage':'Урон двумя руками',
  'versatile damage':'Урон двумя руками', 'versatile damage dice':'Кости урона двумя руками',
  'stealth disadvantage':'Помеха на Скрытность', 'add con modifier':'Добавить модификатор Телосложения',
  'add dex modifier':'Добавить модификатор Ловкости', 'add wis modifier':'Добавить модификатор Мудрости',
  'add another attack':'Добавить ещё одну атаку', 'additional flat bonus to ac':'Дополнительный фиксированный бонус к КБ',
  'additional bonuses from shields and magical items are added separately.':'Бонусы от щитов и магических предметов добавляются отдельно.',
  'ac determines how difficult it is to hit you in combat.':'КБ определяет, насколько трудно попасть по вам в бою.',
  'adds one stat modifier to another (e.g., add dex mod to ac)':'Добавляет модификатор одной характеристики к другой (например, модификатор Ловкости к КБ).',
  'adds or subtracts a fixed value to a stat (e.g., +2 strength)':'Прибавляет или вычитает фиксированное значение (например, +2 к Силе).',
  'active status effects currently affecting your character such as being blinded or stunned.':'Действующие состояния персонажа, например ослепление или ошеломление.',
  'track temporary or permanent buffs and debuffs to your character\'s stats from sources such as spells, blessings or other effects.':'Учитывайте временные и постоянные усиления или ослабления характеристик от заклинаний, благословений и других эффектов.',
  'select a new feat for your character':'Выберите новую черту персонажа', 'choose a new feat for your character':'Выберите новую черту персонажа',
  'choose your advancement':'Выберите улучшение', 'choose your subclass':'Выберите подкласс', 'choose subclass at level':'Выберите подкласс на уровне',
  'ability score increase':'Повышение характеристики', 'ability score improvement':'Улучшение характеристик',
  '+2 to one stat or +1 to two stats':'+2 к одной характеристике или +1 к двум', 'asi points':'Очки улучшения характеристик',
  'basic information':'Основные сведения', 'basic information & stats':'Основные сведения и характеристики',
  'character type':'Тип персонажа', 'your character\'s name':'Имя вашего персонажа',
  'additional details':'Дополнительные сведения', 'additional properties':'Дополнительные свойства',
  'additional notes about this adjustment':'Дополнительные заметки об изменении',
  'brief description':'Краткое описание', 'a brief description':'Краткое описание',
  'he/him':'Он/его', 'she/her':'Она/её', 'they/them':'Они/их',
  'alive':'Жив', 'dead':'Мёртв', 'status':'Состояние', 'successes':'Успехи', 'failures':'Провалы',
  'walk':'Ходьба', 'walk speed':'Скорость ходьбы', 'swim':'Плавание', 'swim speed':'Скорость плавания',
  'climb':'Лазание', 'climb speed':'Скорость лазания', 'burrow':'Рытьё', 'burrow speed':'Скорость рытья', 'fly speed':'Скорость полёта',
  'spellcasting ability':'Заклинательная характеристика', 'spell save dc':'Сл спасброска от заклинаний',
  'spell attack bonus':'Бонус атаки заклинанием', 'casting type':'Тип накладывания', 'max spell level':'Максимальный уровень заклинаний',
  'cast spell':'Наложить заклинание', 'attack spells':'Атакующие заклинания', 'attack spells only':'Только атакующие заклинания',
  'all spells':'Все заклинания', 'known':'Известные', 'choose spell slot level':'Выберите уровень ячейки', 'at higher levels':'На более высоких уровнях',
  'custom instructions':'Дополнительные инструкции',
  'cantrips are level 0, max is 9':'Заговоры имеют уровень 0; максимальный уровень заклинания — 9.',
  'default: 8 + spellcasting mod + proficiency':'По умолчанию: 8 + модификатор заклинательной характеристики + бонус умения',
  'this character is not a spellcaster.':'Этот персонаж не использует заклинания.',
  'you don\'t have any spells ready. go to your spell book and add a spell!':'У вас нет готовых заклинаний. Откройте книгу заклинаний и добавьте заклинание.',
  'you don\'t have any weapons equipped. go to your inventory and equip a weapon!':'У вас нет оружия в руках. Откройте инвентарь и возьмите оружие.',
  'roll hit dice to restore hp':'Бросьте кости хитов, чтобы восстановить ОЗ',
  'no hit dice remaining. take a long rest to recover them.':'Кости хитов закончились. Совершите продолжительный отдых, чтобы восстановить их.',
  'you have no hit dice remaining. you must take a long rest to regain hit dice.':'Кости хитов закончились. Для их восстановления нужен продолжительный отдых.',
  'dice expression':'Формула броска', 'number of dice':'Количество костей', 'type of dice':'Тип костей',
  'select die type':'Выберите тип кости', 'no modifier':'Без модификатора', 'notation':'Обозначение',
  'input your manual roll results':'Введите результаты броска вручную', 'what did you roll?':'Какой результат выпал?',
  'sum of the dice':'Сумма результатов', 'highest of the dice':'Наибольший результат', 'lowest of the dice':'Наименьший результат',
  'quick roll with default settings':'Быстрый бросок с настройками по умолчанию', 'add a message to your roll':'Добавьте сообщение к броску',
  'roll initiative':'Бросить инициативу', 'initiative rolled':'Инициатива определена', 'rolled':'Бросок выполнен', 'rolling':'Бросок…',
  'total':'Итого', 'd4':'к4', 'd6':'к6', 'd8':'к8', 'd10':'к10', 'd12':'к12', 'd20':'к20', 'd100':'к100',
  'campaign settings':'Настройки кампании', 'campaign name':'Название кампании', 'campaign id':'ID кампании',
  'campaign pacing mode':'Темп кампании', 'adventure':'Приключение', 'downtime':'Спокойная игра', 'downtime mode':'Режим спокойной игры',
  'choose between adventure mode for active questing and exploration, or downtime mode for a relaxed slice-of-life experience. in downtime mode, quests are off.':'Выберите приключение для активного выполнения заданий и исследования или спокойную игру для повседневных сцен без спешки. В режиме спокойной игры задания отключены.',
  'narration model':'Модель повествования', 'select franz\'s narration model.':'Выберите модель повествования Франца.',
  'standard models':'Стандартные модели', 'premium models':'Премиальные модели', 'included in your plan':'Включено в вашу подписку',
  'info about narration model':'Сведения о модели повествования',
  'this model only affects franz\'s narration messages. it does not apply during combat.':'Эта модель используется для повествования Франца и не применяется в бою.',
  'hide unknown entities':'Скрывать неизвестные объекты', 'hide entities until they are discovered in-game':'Скрывать объекты, пока они не будут обнаружены в игре',
  'message font size':'Размер шрифта сообщений', 'select font size':'Выберите размер шрифта',
  'adjust the font size for messages in the chat.':'Измените размер шрифта сообщений в чате.',
  'sound effects':'Звуковые эффекты', 'play sound effects for dice rolls.':'Воспроизводить звуковые эффекты бросков костей.',
  'auto play audio':'Автоматическое воспроизведение', 'automatically play audio for new messages from the gm or players.':'Автоматически воспроизводить озвучку новых сообщений мастера или игроков.',
  'automatic audio enabled':'Автоматическая озвучка включена', 'would you like to automatically play audio for new messages?':'Включить автоматическое воспроизведение озвучки новых сообщений?',
  'text-to-speech is available on paid plans. upgrade your account to automatically play audio for new messages.':'Озвучка доступна в платных подписках. Улучшите подписку для автоматического воспроизведения новых сообщений.',
  'upgrade for text to speech':'Улучшить подписку для озвучки', 'upgrade to enable auto tts':'Улучшить подписку для автоматической озвучки',
  'upgrade your plan to generate text to speech':'Улучшите подписку для создания озвучки',
  'automatic working context management':'Автоматическое управление рабочим контекстом', 'automatic context management':'Автоматическое управление контекстом',
  'ai will research and regularly update the working context. recommended to leave on unless you want complete manual control over the working context.':'ИИ будет изучать и регулярно обновлять рабочий контекст. Оставьте эту функцию включённой, если не хотите полностью управлять контекстом вручную.',
  'only the host can change this setting':'Только ведущий кампании может изменить эту настройку',
  'only the campaign host can modify this setting.':'Только ведущий кампании может изменить эту настройку.',
  'only the campaign host can modify these settings.':'Только ведущий кампании может изменить эти настройки.',
  'languages are experimental, and we have not validated performance in any language other than english. if you speak another language, please let us know how it goes!':'Поддержка языков экспериментальная. Работа проверена только на английском. Если вы играете на другом языке, расскажите о результатах.',
  'info panel':'Панель сведений', 'sidebar':'Боковая панель', 'collapse sidebar':'Свернуть боковую панель',
  'expand sidebar':'Развернуть боковую панель', 'navigation':'Навигация', 'open navigation':'Открыть навигацию',
  'quick settings':'Быстрые настройки', 'show map':'Показать карту', 'hide map':'Скрыть карту', 'pop out map':'Открыть карту отдельно',
  'world map':'Карта мира', 'battle map':'Поле боя', 'turn order':'Порядок ходов', 'party':'Группа',
  'party characters':'Персонажи группы', 'other characters':'Другие персонажи', 'other nearby characters':'Другие персонажи поблизости',
  'key characters (closest)':'Важные персонажи (рядом)', 'nearby locations':'Места поблизости', 'nearby points of interest':'Интересные места поблизости',
  'current area':'Текущая область', 'current scene':'Текущая сцена', 'current quest':'Текущее задание', 'current step':'Текущий этап',
  'scene':'Сцена', 'plot':'Сюжет', 'plot summary':'Краткое изложение сюжета', 'narrative':'Повествование', 'narrative context':'Контекст повествования',
  'a high-level overview of the current story arc and major plot points to help franz keep track of the story. franz rewrites this on every turn.':'Обзор текущей сюжетной линии и ключевых событий, который помогает Францу следить за сюжетом. Франц обновляет его на каждом ходу.',
  'the narrative includes a concise summary of the current campaign plot. you can edit it to help steer franz.':'Повествование содержит краткое изложение сюжета кампании. Измените его, чтобы направить Франца.',
  'the current scene is the default context provided to franz for each turn. use context blocks to add additional context for world elements such as lore, factions, or additional character information.':'Текущая сцена передаётся Францу на каждом ходу. Добавляйте блоки контекста для сведений о мире, фракциях и персонажах.',
  'working context shows all of the context that is prepared for franz each turn, except for @mentioned entities or anything researched after receiving your message.':'Рабочий контекст показывает сведения, подготовленные для Франца на каждом ходу, кроме объектов из @упоминаний и данных, найденных после получения вашего сообщения.',
  'are you having trouble with franz? click here for help.':'Возникли проблемы с Францем? Нажмите здесь для помощи.',
  'franz will only rewrite his most recent message.':'Франц перепишет только своё последнее сообщение.',
  'gm continue mode. space to open and then use arrow keys to navigate.':'Режим продолжения мастера. Нажмите пробел, чтобы открыть, затем используйте стрелки.',
  'continue - gm automatically continues after player messages':'Продолжить — мастер автоматически отвечает после сообщений игроков',
  'manual - gm waits for you to trigger continuation':'Вручную — мастер ждёт вашей команды для продолжения',
  'players only - message only visible to players, not the gm':'Только игроки — сообщение видно игрокам, мастер его не видит',
  'player-only message':'Сообщение только для игроков', 'get suggested actions':'Предложить действия',
  'rewrite message':'Переписать сообщение', 'edit message':'Редактировать сообщение', 'message dropdownmenu':'Меню сообщения',
  'send message':'Отправить сообщение', 'send message (v2)':'Отправить сообщение', 'more actions':'Другие действия',
  'scroll to bottom':'Прокрутить вниз', 'recent transcript':'Недавняя переписка', 'no recent conversation history available.':'Недавняя переписка отсутствует.',
  'tap a message to jump to it':'Нажмите на сообщение, чтобы перейти к нему', 'search messages...':'Поиск сообщений…', 'searching messages...':'Поиск сообщений…',
  'record audio':'Записать голос', 'stop recording':'Остановить запись', 'discard recording':'Удалить запись',
  'send audio':'Отправить запись', 'download audio':'Скачать озвучку', 'processing audio...':'Обработка записи…',
  'loading transcript...':'Загрузка переписки…', 'typing indicator':'Индикатор набора текста',
  'writing instructions':'Инструкции по написанию', 'write your own message...':'Напишите сообщение…',
  'friends & fables is in early access beta. please report any bugs you may find.':'Friends & Fables находится в раннем доступе. Сообщайте о найденных ошибках.',
  'game over':'Игра окончена', 'reincarnate':'Воплотиться в другом персонаже', 're-select your character':'Выбрать персонажа заново',
  'play as another character in this world':'Играть за другого персонажа этого мира',
  'sorry, there was an error. to continue playing, please re-select your character.':'Произошла ошибка. Чтобы продолжить игру, выберите персонажа заново.',
  'current location, characters present, and immediate environment. this is fixed context based on the current location and the structure cannot be edited. if you wish to supply more information, use context blocks.':'Текущее местоположение, присутствующие персонажи и окружение. Структуру этого контекста нельзя редактировать. Для дополнительных сведений используйте блоки контекста.',
  'context agent':'Агент контекста', 'context blocks':'Блоки контекста', 'context block settings':'Настройки блоков контекста',
  'context group priorities & budgets':'Приоритеты и лимиты групп контекста', 'idle context blocks':'Неактивные блоки контекста',
  'idle blocks info':'О неактивных блоках', 'budget exceeded':'Лимит превышен', 'approaching character limit':'Приближение к лимиту символов',
  'increase context limit':'Увеличить лимит контекста', 'increase context limits':'Увеличить лимиты контекста', 'increase limits':'Увеличить лимиты',
  'want more context?':'Нужно больше контекста?', 'expand working context':'Развернуть рабочий контекст', 'close context block settings':'Закрыть настройки блоков контекста',
  'block title (optional)':'Заголовок блока (необязательно)', 'select context type':'Выберите тип контекста',
  'start writing your context block...':'Введите текст блока контекста…', 'search context blocks...':'Поиск блоков контекста…',
  'no context blocks yet':'Блоков контекста пока нет', 'no blocks match your filters':'Нет блоков, соответствующих фильтрам',
  'never expires':'Без срока действия', 'context block actions. use up and down arrow keys to navigate.':'Действия с блоком контекста. Используйте стрелки вверх и вниз.',
  'adjust the priority of the block by dragging it up in the list.':'Перетащите блок выше в списке, чтобы повысить его приоритет.',
  'configure automatic context management and customize budget allocation for each context block type.':'Настройте автоматическое управление контекстом и лимиты для каждого типа блоков.',
  'drag to reorder priority and adjust budget allocation for each context block type.':'Перетаскивайте группы для изменения приоритета и настраивайте их лимиты.',
  'increase the budget for this block type in settings.':'Увеличьте лимит для этого типа блоков в настройках.',
  'idle blocks will automatically become active when space becomes available.':'Неактивные блоки автоматически станут активными, когда освободится место.',
  'context blocks are information that you and the research agent can both add to and edit. use this to pull in additional information about lore, memories, etc.':'Блоки контекста содержат сведения, которые можете добавлять и редактировать вы и агент исследования. Используйте их для сведений о мире, воспоминаний и других данных.',
  'set the percentage of the total context budget that each block type can use. when the total budget is full, blocks from lower priority groups will become idle first. blocks can still be active even if their group exceeds its percentage as long as there\'s total remaining budget overall.':'Укажите долю общего лимита для каждого типа блоков. При заполнении общего лимита первыми отключаются блоки групп с меньшим приоритетом. Группа может превышать свою долю, пока в общем лимите есть свободное место.',
  'about memories':'О воспоминаниях', 'read memories guide':'Руководство по воспоминаниям', 'view memories':'Просмотреть воспоминания',
  'enter memory content...':'Введите текст воспоминания…', 'memory content cannot be empty':'Текст воспоминания не может быть пустым',
  'responding character memories':'Воспоминания отвечающего персонажа', 'if you are talking to a character, we will pull in their character memories at runtime.':'Во время разговора с персонажем его воспоминания добавляются в контекст.',
  'campaign saves':'Сохранения кампании', 'restore campaign':'Восстановить кампанию', 'restoring campaign...':'Восстановление кампании…',
  'restoration details':'Сведения о восстановлении', 'no save points created yet. create your first save point to enable restoration later.':'Сохранений пока нет. Создайте первое сохранение, чтобы позднее восстановить кампанию.',
  'save points allow you to restore your campaign to a previous state. this includes characters, inventory, spells, and monster instances.':'Сохранения позволяют восстановить прежнее состояние кампании, включая персонажей, инвентарь, заклинания и монстров.',
  'quest book':'Книга заданий', 'quest log':'Журнал заданий', 'quest paths':'Пути задания', 'quest prerequisites':'Требования задания',
  'quest prerequisite':'Предварительное задание', 'prerequisite quest':'Предварительное задание', 'quest giver':'Персонаж, выдающий задание',
  'quest location':'Место задания', 'quest step location':'Место этапа задания', 'quest difficulty':'Сложность задания',
  'quest description':'Описание задания', 'quest tags':'Метки задания', 'possible paths':'Возможные пути', 'path taken':'Выбранный путь',
  'step location':'Место этапа', 'starting scene':'Начальная сцена', 'starting message':'Начальное сообщение',
  'starting scene characters':'Персонажи начальной сцены', 'playable characters':'Игровые персонажи', 'in party':'В группе',
  'level requirement':'Требование к уровню', 'minimum level required':'Минимальный уровень', 'xp reward':'Награда опытом',
  'gm hook instructions':'Инструкции мастеру для начала задания', 'gm instructions':'Инструкции мастеру',
  'cancel quest':'Отменить задание', 'keep quest':'Оставить задание', 'complete this quest step':'Завершить этап задания',
  'undo this step - mark as incomplete to redo it':'Отменить этап — отметить как незавершённый для повторного прохождения',
  'all steps have been completed':'Все этапы завершены', 'progress':'Прогресс', 'outcome':'Исход', 'new campaign':'Новая кампания',
  'end encounter':'Завершить бой', 'encounter notes':'Заметки боя', 'about encounter notes':'О заметках боя',
  'toggle encounter notes':'Показать или скрыть заметки боя', 'note content':'Текст заметки', 'note expiration':'Срок действия заметки',
  'no encounter notes yet':'Заметок боя пока нет', 'enter note content...':'Введите текст заметки…',
  'note too long':'Заметка слишком длинная', 'encounter initiated!':'Бой начат!', 'turn order updated':'Порядок ходов обновлён',
  'editing an encounter should only be used if franz made a mistake!':'Редактируйте бой, если Франц допустил ошибку.',
  'edit the encounter in the encounters tab':'Редактируйте бой на вкладке боёв', 'it is not your turn - you will not be able to submit an attack until it is your turn.':'Сейчас не ваш ход. Вы сможете выполнить атаку на своём ходу.',
  'track if this entity has used their reaction this round':'Отмечайте, использовал ли участник реакцию в этом раунде',
  'current state of this entity in the encounter':'Текущее состояние участника боя',
  'map size':'Размер карты', 'map help':'Помощь по карте', 'map layer settings':'Настройки слоёв карты', 'layer settings':'Настройки слоёв',
  'map scale':'Масштаб карты', 'map editor controls':'Управление редактором карты', 'map tools guide':'Руководство по инструментам карты',
  'center map on my character':'Центрировать карту на моём персонаже', 'focus camera on your character':'Переместить камеру к персонажу',
  'fit to screen':'По размеру экрана', 'fit map to screen':'Подогнать карту под экран', 'zoom to fit':'Подогнать масштаб',
  'zoom to full map':'Показать всю карту', 'zoom to entities':'Показать объекты', 'zoom in':'Увеличить масштаб', 'zoom out':'Уменьшить масштаб',
  'toggle map zoom':'Изменить масштаб карты', 'toggle npc list':'Показать или скрыть список НИП',
  'open world overview':'Открыть обзор мира', 'toggle side panel lock':'Закрепить или открепить боковую панель',
  'lock side panel':'Закрепить боковую панель', 'side panel is locked':'Боковая панель закреплена',
  'points of interest':'Интересные места', 'point of interest':'Интересное место', 'poi':'Интересное место', 'pois':'Интересные места',
  'areas':'Области', 'area':'Область', 'npc':'НИП', 'npcs':'НИП', 'monsters':'Монстры', 'monster':'Монстр',
  'lore':'Сведения о мире', 'view lore':'Просмотреть сведения о мире', 'view world':'Просмотреть мир', 'world information':'Сведения о мире',
  'position':'Положение', 'rotation':'Поворот', 'coordinates':'Координаты', 'x position':'Положение X', 'y position':'Положение Y',
  'x coordinate':'Координата X', 'y coordinate':'Координата Y', 'width (tiles)':'Ширина (клетки)', 'height (tiles)':'Высота (клетки)',
  'position on battlemap':'Положение на поле боя', 'move party here':'Переместить группу сюда', 'place entities':'Разместить объекты',
  'show label':'Показать подпись', 'hide image':'Скрыть изображение', 'font size':'Размер шрифта', 'border color':'Цвет границы',
  'border only':'Только границы', 'opacity':'Непрозрачность', 'pan':'Перемещение карты', 'measure':'Измерить',
  'erase':'Стереть', 'lock':'Закрепить', 'box select':'Выделение рамкой', 'unplaced entities':'Неразмещённые объекты', 'unplace':'Убрать с карты',
  'pending changes':'Ожидающие изменения', 'save changes':'Сохранить изменения', 'unsaved changes':'Несохранённые изменения',
  'continue editing':'Продолжить редактирование', 'exit without saving':'Выйти без сохранения',
  'type delete to confirm':'Введите DELETE для подтверждения', 'toggle visibility of this layer':'Показать или скрыть этот слой',
  'prevent editing or moving items in this layer':'Запретить редактирование и перемещение объектов этого слоя',
  'show only borders without fill color':'Показывать только границы без заливки', 'show only outlines without images':'Показывать только контуры без изображений',
  'on this map, 1 unit equals approximately 100 meters of distance, which translates to about 1 minute of walking time for characters.':'Одна единица этой карты соответствует примерно 100 метрам, то есть около минуты ходьбы для персонажа.',
  'no entities here':'Здесь нет объектов', 'no details available':'Сведения отсутствуют', 'unknown location':'Неизвестное место',
  'no current location information available.':'Сведения о текущем местоположении отсутствуют.', 'party is not at a specific point of interest.':'Группа находится вне интересного места.',
  'invite':'Пригласить', 'invite them':'Пригласить', 'kick player':'Исключить игрока',
  'invite friends to play as these characters. anyone not chosen by another player will be played by ai.':'Пригласите друзей играть за этих персонажей. Персонажами, которых никто не выбрал, будет управлять ИИ.',
  'are you sure you want to kick this player? they will be removed from the campaign.':'Исключить этого игрока из кампании?',
  'choose a destination':'Выберите место назначения', 'choose action':'Выберите действие', 'choose your attack':'Выберите атаку',
  'select status':'Выберите состояние', 'select a feat':'Выберите черту', 'select a lore page':'Выберите страницу сведений о мире',
  'select entity type':'Выберите тип объекта', 'select style':'Выберите стиль', 'select vantage':'Выберите ракурс',
  'generate scene':'Создать сцену', 'generate scene image':'Создать изображение сцены', 'generating scene':'Создание сцены…',
  'key subjects':'Основные объекты', 'match reference images':'Соответствовать изображениям-образцам', 'vantage':'Ракурс',
  'fantasy illustration':'Фэнтезийная иллюстрация', 'digital art':'Цифровой рисунок', 'photorealistic':'Фотореализм', 'anime style':'Стиль аниме',
  'select the reference images and descriptions of the main subjects you want featured in the image.':'Выберите изображения-образцы и описания основных объектов будущего изображения.',
  'best results with 4 or fewer subjects (1 location + 3 characters/items). more subjects may reduce quality.':'Лучшие результаты получаются с четырьмя объектами или меньше (одно место и три персонажа или предмета). Большее количество может снизить качество.',
  'describe the mood or composition (e.g., \'celebrating a victory\', \'tense standoff\')':'Опишите настроение или композицию (например, «празднование победы» или «напряжённое противостояние»)',
  'image downloaded':'Изображение скачано', 'image updated':'Изображение обновлено', 'found cached image':'Найдено сохранённое изображение',
  'content required':'Требуется текст', 'type required':'Требуется тип', 'failed':'Не удалось', 'permission denied':'Доступ запрещён',
  'unsupported content':'Неподдерживаемое содержимое', 'generation failed':'Не удалось создать', 'generation started':'Создание началось',
  'fallback model used':'Использована резервная модель', 'no text selected':'Текст не выделен', 'all resolved':'Всё обработано',
  'accept all':'Принять всё', 'decline':'Отклонить', 'decline all':'Отклонить всё', 'declined':'Отклонено', 'dismissed':'Закрыто',
  'thanks for the feedback!':'Спасибо за отзыв!', 'thanks for the rating!':'Спасибо за оценку!',
  'feedback':'Отзыв', 'tropes feedback':'Отзыв о клише', 'type your feedback here...':'Введите отзыв…',
  'which stat had issues?':'С какой характеристикой возникла проблема?', 'other stat issue':'Другая проблема с характеристиками',
  'please give feedback to continue (click thumbs up or down)':'Для продолжения оцените ответ (нажмите палец вверх или вниз)',
  'thumbs down - negative feedback':'Палец вниз — отрицательная оценка', 'thumbs up - gpositive feedback':'Палец вверх — положительная оценка',
  'filter':'Фильтр', 'all':'Все', 'all items':'Все предметы', 'any':'Любой', 'any time':'В любое время',
  'clear':'Очистить', 'clear all':'Очистить всё', 'clear search':'Очистить поиск', 'clear all filters':'Сбросить все фильтры',
  'retry':'Повторить', 'undo':'Отменить', 'undo all':'Отменить всё', 'confirm':'Подтвердить', 'apply':'Применить',
  'submit':'Отправить', 'open':'Открыть', 'reset':'Сбросить', 'yes':'Да', 'no':'Нет', 'unknown':'Неизвестно',
  'available':'Доступно', 'unlimited':'Без ограничений', 'newest':'Сначала новые', 'oldest':'Сначала старые',
  'newest first':'Сначала новые', 'oldest first':'Сначала старые', 'order...':'Порядок…', 'extra small':'Очень мелкий', 'extra large':'Очень крупный',
  'simple':'Простой', 'never':'Никогда', 'note':'Примечание', 'title':'Заголовок', 'name':'Название',
  'tags':'Метки', 'tag':'Метка', 'type':'Тип', 'value':'Значение', 'cost':'Стоимость', 'weight':'Вес', 'weight (lbs.)':'Вес (фунты)',
  'common':'Обычный', 'uncommon':'Необычный', 'rare':'Редкий', 'very rare':'Очень редкий', 'legendary':'Легендарный',
  'cloned from':'Копия', 'clone':'Создать копию', 'clones':'Копии', 'author\'s note':'Заметка автора',
  'public':'Публичный', 'private':'Приватный', 'unlisted':'По ссылке', 'visibility':'Видимость', 'untitled':'Без названия',
  'new page':'Новая страница', 'new pages':'Новые страницы', 'no lore pages yet.':'Страниц сведений о мире пока нет.',
  'page title...':'Заголовок страницы…', 'this page is empty.':'Страница пуста.', 'this page is empty. click edit to add content.':'Страница пуста. Нажмите «Редактировать», чтобы добавить текст.',
  'this content is private and cannot be shared. only the author can change its visibility.':'Это содержимое приватное, и им нельзя поделиться. Только автор может изменить видимость.',
  'you do not have permission to edit this.':'У вас нет разрешения на редактирование.',
  'profile':'Профиль', 'username':'Имя пользователя', 'choose your username':'Выберите имя пользователя',
  'creator':'Автор', 'your worlds':'Ваши миры', 'explore all':'Посмотреть всё', 'begin':'Начать', 'new':'Новое',
  'copied':'Скопировано', 'copy campaign id':'Копировать ID кампании', 'copy link':'Копировать ссылку', 'link copied to clipboard':'Ссылка скопирована',
  'campaign id copied':'ID кампании скопирован', 'setting saved':'Настройка сохранена', 'setting updated':'Настройка обновлена',
  'language updated':'Язык обновлён', 'pacing mode updated':'Темп кампании обновлён', 'narration model updated':'Модель повествования обновлена',
  'too many requests!':'Слишком много запросов!', 'too many attempts.':'Слишком много попыток.', 'this action cannot be undone.':'Это действие нельзя отменить.',
  'you have unsaved changes. are you sure you want to close?':'Есть несохранённые изменения. Закрыть окно?',
  'you have unsaved changes. are you sure you want to exit edit mode? your changes will be lost.':'Есть несохранённые изменения. Выйти из редактирования? Изменения будут потеряны.',
  'this will delete all messages after and including this one. this action cannot be undone.':'Это сообщение и все последующие будут удалены. Действие нельзя отменить.',
  'this will undo all inventory changes and cannot be reversed.':'Все изменения инвентаря будут отменены. Вернуть их будет невозможно.',
  'this will undo all character sheet changes.':'Все изменения листа персонажа будут отменены.', 'this will undo all movement changes.':'Все перемещения будут отменены.',
  'this will reset the relationship score to its previous value.':'Показатель отношений вернётся к прежнему значению.',
  'you were not charged any credits.':'Кредиты не списаны.', 'your session has expired. please log back in!':'Сессия истекла. Войдите снова.',
  'error details':'Сведения об ошибке', 'errors':'Ошибки', 'warning':'Предупреждение', 'keyboard shortcuts':'Сочетания клавиш',
  'search rolls...':'Поиск бросков…', 'search characters...':'Поиск персонажей…', 'search items...':'Поиск предметов…',
  'search monsters...':'Поиск монстров…', 'search quests...':'Поиск заданий…', 'search entities...':'Поиск объектов…',
  'click to change image':'Нажмите, чтобы изменить изображение', 'click to edit description':'Нажмите, чтобы изменить описание',
  'click to learn more':'Нажмите, чтобы узнать больше', 'click to add credits':'Нажмите, чтобы добавить кредиты',
  'click to add plot summary...':'Нажмите, чтобы добавить краткое изложение сюжета…', 'enter plot summary...':'Введите краткое изложение сюжета…',
  'additional instructions (optional)':'Дополнительные инструкции (необязательно)', 'add description...':'Добавьте описание…',
  'a fast and powerful model.':'Быстрая и мощная модель.', 'a fast, capable model for creative narration.':'Быстрая модель для творческого повествования.',
  'a powerful premium model, excellent for creative writing and complex scenarios.':'Мощная премиальная модель для творческого письма и сложных сценариев.',
  'the fastest and most reliable model.':'Самая быстрая и надёжная модель.',
  'google\'s most advanced model. exceptional at complex reasoning and creative writing.':'Самая продвинутая модель Google для сложных рассуждений и творческого письма.',
  'xai\'s most advanced model. exceptional at complex reasoning and creative writing.':'Самая продвинутая модель xAI для сложных рассуждений и творческого письма.',
  "aliases":"Другие имена",
  "add aliases...":"Добавьте другие имена…",
  "maximum 3 aliases allowed":"Можно указать не более трёх других имён",
  "ally targets":"Союзные цели",
  "enemy targets":"Вражеские цели",
  "auto-calculated if empty":"Вычисляется автоматически, если оставить пустым",
  "barbarian unarmored:":"Без доспехов у варвара:",
  "base:":"Базовое значение:",
  "adjusted:":"С учётом изменений:",
  "dexterity modifier":"Модификатор Ловкости",
  "dice roll":"Бросок костей",
  "difficulty class (dc)":"Сложность (Сл)",
  "does the target make a save?":"Цель совершает спасбросок?",
  "does this spell need an attack roll?":"Для заклинания нужен бросок атаки?",
  "friendly":"Дружелюбный",
  "hostile":"Враждебный",
  "neutral":"Нейтральный",
  "melee":"Ближний бой",
  "ranged":"Дальний бой",
  "list view":"Список",
  "graph view":"Граф",
  "members":"Участники",
  "modifier value":"Значение модификатора",
  "mod":"Модификатор",
  "modifier to":"модификатор к",
  "no armor:":"Без доспехов:",
  "no class selected for this character":"Класс персонажа не выбран",
  "no features or feats available":"Нет доступных умений или черт",
  "no spell slot available":"Нет доступной ячейки заклинания",
  "no spell slots available":"Нет доступных ячеек заклинаний",
  "no subclasses available.":"Нет доступных подклассов.",
  "no feats are available in this world. create some feats first to add them to your character.":"В этом мире пока нет черт. Создайте их, чтобы добавить персонажу.",
  "note: if you want to change this ac value, you can equip armor and modify the base ac of the armor.":"Чтобы изменить КБ, наденьте доспехи и измените их базовый класс брони.",
  "cannot add multiple feats at the same level":"На одном уровне можно получить только одну черту",
  "only one feat can be taken per level. please adjust the duplicate levels.":"На каждом уровне можно получить только одну черту. Измените повторяющиеся уровни.",
  "non playable":"Неигровой",
  "playable":"Игровой",
  "play as":"Играть за",
  "play as character":"Играть за персонажа",
  "party full":"Группа заполнена",
  "please fill out a name, appearance, pronouns, race, and class!":"Укажите имя, внешность, местоимения, расу и класс.",
  "please select a location":"Выберите место",
  "please wait":"Подождите",
  "positive relationship":"Положительные отношения",
  "negative relationship":"Отрицательные отношения",
  "preview:":"Предпросмотр:",
  "rate limit exceeded":"Превышен лимит запросов",
  "request already processed":"Запрос уже обработан",
  "resources derived from your character's class, such as a barbarian's rage or a monk's focus points.":"Ресурсы класса персонажа, например ярость варвара или очки фокусировки монаха.",
  "roll already submitted":"Бросок уже отправлен",
  "roll twice, take higher":"Бросьте дважды и выберите больший результат",
  "roll twice, take lower":"Бросьте дважды и выберите меньший результат",
  "standard roll":"Обычный бросок",
  "saving throw required":"Требуется спасбросок",
  "saving throw type":"Тип спасброска",
  "spell slot level":"Уровень ячейки заклинания",
  "spells prepared":"Подготовленные заклинания",
  "spells ready":"Готовые заклинания",
  "spell slots reset":"Ячейки заклинаний восстановлены",
  "sets a stat to a specific value (e.g., ac = 15)":"Задаёт конкретное значение характеристики (например, КБ = 15).",
  "special abilities or enhancements your character gains at certain levels instead of taking an ability score improvement.":"Особые способности или улучшения, которые персонаж получает на определённых уровнях вместо улучшения характеристик.",
  "spells are not available in the workshop. add this character to a world first.":"Заклинания недоступны в мастерской. Сначала добавьте персонажа в мир.",
  "character name already exists":"Персонаж с таким именем уже существует",
  "the character you're looking for doesn't exist or has been deleted.":"Этот персонаж не существует или был удалён.",
  "host does not have enough credits.":"У ведущего кампании недостаточно кредитов.",
  "this cannot be undone.":"Это нельзя отменить.",
  "remove member?":"Удалить участника?",
  "delete action?":"Удалить действие?",
  "delete relationship?":"Удалить отношения?",
  "removal condition (optional)":"Условие снятия (необязательно)",
  "message (optional)":"Сообщение (необязательно)",
  "note (optional)":"Заметка (необязательно)",
  "click and drag to pan. mouse-wheel to zoom.":"Перетаскивайте для перемещения. Меняйте масштаб колёсиком мыши.",
  "describe character appearance":"Опишите внешность персонажа",
  "describe character backstory":"Опишите предысторию персонажа",
  "describe character mannerisms":"Опишите манеры персонажа",
  "describe character personality":"Опишите характер персонажа",
  "describe your character here...":"Опишите персонажа…",
  "describe your faction here...":"Опишите фракцию…",
  "describe your attack... (e.g., 'i swing my sword in a wide arc')":"Опишите атаку (например: «Я замахиваюсь мечом по широкой дуге»).",
  "from srd":"Из SRD",
  "from workshop":"Из мастерской",
  "from world":"Из мира",
  "custom":"Своё значение",
  "custom tab":"Дополнительная вкладка",
  "quantity updated":"Количество изменено",
  "currency updated":"Валюта изменена",
  "list":"Список",
  "normal":"Обычный",
  "enter cost":"Введите стоимость",
  "enter weight":"Введите вес",
  "item type":"Тип предмета",
  "item properties":"Свойства предмета",
  "item bonuses":"Бонусы предмета",
  "properties":"Свойства",
  "other properties":"Другие свойства",
  "equip slot (optional)":"Место снаряжения (необязательно)",
  "flat ac bonus (optional)":"Фиксированный бонус КБ (необязательно)",
  "flat bonus":"Фиксированный бонус",
  "flat bonuses":"Фиксированные бонусы",
  "fixed bonus":"Фиксированный бонус",
  "flat adjustments":"Фиксированные изменения",
  "override values":"Замена значений",
  "modifier stat":"Добавляемый модификатор",
  "target stat":"Изменяемая характеристика",
  "max modifier (optional)":"Максимум модификатора (необязательно)",
  "maximum ability modifier that can be added":"Максимальный добавляемый модификатор характеристики",
  "normal range (ft)":"Обычная дистанция (футы)",
  "long range (ft)":"Предельная дистанция (футы)",
  "dice number":"Количество костей",
  "dice size":"Граней у кости",
  "gear":"Снаряжение",
  "heavy":"Тяжёлое",
  "magic item":"Магический предмет",
  "rarity":"Редкость",
  "slot":"Место снаряжения",
  "immunities":"Иммунитеты",
  "resistances":"Сопротивления",
  "resistances & immunities":"Сопротивления и иммунитеты",
  "imposes disadvantage on stealth checks":"Даёт помеху на проверки Скрытности",
  "this armor imposes disadvantage on stealth checks":"Эти доспехи дают помеху на проверки Скрытности.",
  "small creatures have disadvantage on attack rolls with heavy weapons.":"Маленькие существа совершают атаки тяжёлым оружием с помехой.",
  "please correct the form errors before submitting":"Исправьте ошибки формы перед отправкой",
  "what does the item do?":"Как действует предмет?",
  "what does the item look like?":"Как выглядит предмет?",
  "what is the item called?":"Как называется предмет?",
  "describe your item...":"Опишите предмет…",
  "this weapon adds 5 feet to your reach when you attack with it.":"Атака этим оружием увеличивает досягаемость на 5 футов.",
  "added":"Добавлено",
  "up to":"не более",
  "select":"Выбрать",
  "select cost unit":"Выберите единицу стоимости",
  "select equip slot":"Выберите место снаряжения",
  "select item category":"Выберите категорию предмета",
  "select item rarity":"Выберите редкость предмета",
  "select targets":"Выберите цели",
  "open attack dropdown menu":"Открыть меню атаки",
  "open menu":"Открыть меню",
  "loading custom classes...":"Загрузка дополнительных классов…",
  "loading custom races...":"Загрузка дополнительных рас…",
  "loading features...":"Загрузка умений…",
  "loading subclasses...":"Загрузка подклассов…",
  "error loading memories":"Не удалось загрузить воспоминания",
  "error updating character":"Не удалось обновить персонажа",
  "briefing":"Вводные сведения",
  "character briefing":"Вводные сведения о персонаже",
  "character positioning":"Размещение персонажей",
  "arrival scene setup":"Настройка сцены прибытия",
  "completion scene setup":"Настройка сцены завершения",
  "card image":"Изображение карточки",
  "one-shot":"Короткое приключение",
  "one-shot description":"Описание короткого приключения",
  "share one-shot":"Поделиться коротким приключением",
  "start one-shot":"Начать короткое приключение",
  "no paths defined":"Пути не заданы",
  "no starting location":"Начальное место не выбрано",
  "path":"Путь",
  "quest title":"Название задания",
  "trigger":"Условие",
  "source":"Источник",
  "fit view":"Подогнать масштаб",
  "toggle interactivity":"Переключить взаимодействие",
  "auto layout":"Расположить автоматически",
  "back to quest display":"Вернуться к заданию",
  "exit quest editor":"Выйти из редактора задания",
  "cannot delete connection":"Нельзя удалить связь",
  "invalid connection":"Недопустимая связь",
  "path already connected":"Путь уже связан",
  "maximum paths reached":"Достигнут лимит путей",
  "step limit reached":"Достигнут лимит этапов",
  "maximum tags reached":"Достигнут лимит меток",
  "max party members reached":"Достигнут лимит участников группы",
  "poi cover image (optional)":"Обложка места (необязательно)",
  "poi map image (optional)":"Карта места (необязательно)",
  "quest cover image":"Обложка задания",
  "quest giver (optional)":"Персонаж, выдающий задание (необязательно)",
  "select difficulty...":"Выберите сложность…",
  "select up to 3 tags...":"Выберите не более трёх меток…",
  "choose where this quest step takes place":"Выберите место этапа задания",
  "players must complete the another quest before starting this one.":"Игроки должны завершить другое задание, прежде чем начать это.",
  "set a minimum character level required to start this quest.":"Укажите минимальный уровень персонажа для начала задания.",
  "the character who will give this quest to players":"Персонаж, который выдаст задание игрокам",
  "define the paths that lead from this step to other steps":"Задайте пути от этого этапа к другим",
  "add paths to connect this step to other steps":"Добавьте пути, чтобы связать этот этап с другими",
  "set the scene for this step":"Задайте сцену этого этапа",
  "set the scene that occurs when this path is completed.":"Задайте сцену после прохождения этого пути.",
  "add characters to create your starting scene":"Добавьте персонажей для начальной сцены",
  "no characters selected. add characters to place them on the map.":"Персонажи не выбраны. Добавьте их для размещения на карте.",
  "please add at least one party character to create your one-shot.":"Добавьте хотя бы одного персонажа группы для создания короткого приключения.",
  "instructions for the game master on how to run this step...":"Инструкции мастеру о проведении этапа…",
  "update quest details such as the title, description, and hook.":"Измените название, описание и завязку задания.",
  "update your one-shot adventure details.":"Измените сведения о коротком приключении.",
  "enter an opening message from the gm for your one-shot adventure...":"Введите вступительное сообщение мастера для короткого приключения…",
  "enter gm instructions for presenting this quest...":"Введите инструкции мастеру для представления задания…",
  "what triggers this path...":"Условие выбора этого пути…",
  "enter minimum level (1-20)":"Введите минимальный уровень (1–20)",
  "describe the one-shot adventure you want to generate...":"Опишите короткое приключение для создания…",
  "describe the quest you want to generate...":"Опишите задание для создания…",
  "enter the adventure description...":"Введите описание приключения…",
  "describe what this quest step should accomplish...":"Опишите цель этапа задания…",
  "describe what happens when this path is taken...":"Опишите события при выборе этого пути…",
  "describe how this location appears for this trigger...":"Опишите вид места при этом условии…",
  "describe the visual appearance for this trigger...":"Опишите внешний вид при этом условии…",
  "select a character to auto-populate the location":"Выберите персонажа для автоматического выбора места",
  "select a character to give this quest...":"Выберите персонажа, выдающего задание…",
  "select the character who gives this quest (optional)...":"Выберите персонажа, выдающего задание (необязательно)…",
  "select the character who gives this quest...":"Выберите персонажа, выдающего задание…",
  "select location for this step...":"Выберите место этапа…",
  "select a prerequisite quest...":"Выберите предварительное задание…",
  "📍 location auto-populated. you can change it if needed.":"📍 Место выбрано автоматически. При необходимости измените его.",
  "✨ generate one-shot with ai":"✨ Создать короткое приключение с ИИ",
  "✨ generate quest with ai":"✨ Создать задание с ИИ",
  "✨ generate quest step with ai":"✨ Создать этап задания с ИИ",
  // Product/model names remain their official spelling everywhere.
  'deepseek v4 flash':'DeepSeek V4 Flash', 'gemini 3.1 pro':'Gemini 3.1 Pro', 'grok 4.7':'Grok 4.7',
  'glm-5':'GLM-5', 'hy-3':'Hy-3', 'fenix':'Fenix', 'openai':'OpenAI', 'openrouter':'OpenRouter', 'groq':'Groq',
};

// Shared CRUD controls use grammatical forms rather than model-generated wording.
const entities: Record<string, { one: string; many: string; object: string; genitive: string; created: string; updated: string; deleted: string; selected: string; found: string }> = {
  character:{one:'персонаж',many:'персонажи',object:'персонажа',genitive:'персонажа',created:'Персонаж создан',updated:'Персонаж обновлён',deleted:'Персонаж удалён',selected:'Персонаж не выбран',found:'Персонажи не найдены'},
  item:{one:'предмет',many:'предметы',object:'предмет',genitive:'предмета',created:'Предмет создан',updated:'Предмет обновлён',deleted:'Предмет удалён',selected:'Предмет не выбран',found:'Предметы не найдены'},
  spell:{one:'заклинание',many:'заклинания',object:'заклинание',genitive:'заклинания',created:'Заклинание создано',updated:'Заклинание обновлено',deleted:'Заклинание удалено',selected:'Заклинание не выбрано',found:'Заклинания не найдены'},
  feat:{one:'черта',many:'черты',object:'черту',genitive:'черты',created:'Черта создана',updated:'Черта обновлена',deleted:'Черта удалена',selected:'Черта не выбрана',found:'Черты не найдены'},
  class:{one:'класс',many:'классы',object:'класс',genitive:'класса',created:'Класс создан',updated:'Класс обновлён',deleted:'Класс удалён',selected:'Класс не выбран',found:'Классы не найдены'},
  subclass:{one:'подкласс',many:'подклассы',object:'подкласс',genitive:'подкласса',created:'Подкласс создан',updated:'Подкласс обновлён',deleted:'Подкласс удалён',selected:'Подкласс не выбран',found:'Подклассы не найдены'},
  race:{one:'раса',many:'расы',object:'расу',genitive:'расы',created:'Раса создана',updated:'Раса обновлена',deleted:'Раса удалена',selected:'Раса не выбрана',found:'Расы не найдены'},
  faction:{one:'фракция',many:'фракции',object:'фракцию',genitive:'фракции',created:'Фракция создана',updated:'Фракция обновлена',deleted:'Фракция удалена',selected:'Фракция не выбрана',found:'Фракции не найдены'},
  location:{one:'место',many:'места',object:'место',genitive:'места',created:'Место создано',updated:'Место обновлено',deleted:'Место удалено',selected:'Место не выбрано',found:'Места не найдены'},
  monster:{one:'монстр',many:'монстры',object:'монстра',genitive:'монстра',created:'Монстр создан',updated:'Монстр обновлён',deleted:'Монстр удалён',selected:'Монстр не выбран',found:'Монстры не найдены'},
  quest:{one:'задание',many:'задания',object:'задание',genitive:'задания',created:'Задание создано',updated:'Задание обновлено',deleted:'Задание удалено',selected:'Задание не выбрано',found:'Задания не найдены'},
  'quest step':{one:'этап задания',many:'этапы задания',object:'этап задания',genitive:'этапа задания',created:'Этап задания создан',updated:'Этап задания обновлён',deleted:'Этап задания удалён',selected:'Этап задания не выбран',found:'Этапы задания не найдены'},
  path:{one:'путь',many:'пути',object:'путь',genitive:'пути',created:'Путь создан',updated:'Путь обновлён',deleted:'Путь удалён',selected:'Путь не выбран',found:'Пути не найдены'},
  relationship:{one:'отношения',many:'отношения',object:'отношения',genitive:'отношений',created:'Отношения созданы',updated:'Отношения обновлены',deleted:'Отношения удалены',selected:'Отношения не выбраны',found:'Отношения не найдены'},
  memory:{one:'воспоминание',many:'воспоминания',object:'воспоминание',genitive:'воспоминания',created:'Воспоминание создано',updated:'Воспоминание обновлено',deleted:'Воспоминание удалено',selected:'Воспоминание не выбрано',found:'Воспоминания не найдены'},
  'one-shot':{one:'короткое приключение',many:'короткие приключения',object:'короткое приключение',genitive:'короткого приключения',created:'Короткое приключение создано',updated:'Короткое приключение обновлено',deleted:'Короткое приключение удалено',selected:'Короткое приключение не выбрано',found:'Короткие приключения не найдены'},
};
const add = (source: string, target: string): void => { SHARED_INTERFACE_GLOSSARY[source] ??= target; };
for (const [entity, forms] of Object.entries(entities)) {
  for (const [verb, russian] of Object.entries({add:'Добавить',create:'Создать',edit:'Редактировать',delete:'Удалить',remove:'Удалить',save:'Сохранить',view:'Просмотреть',select:'Выберите',generate:'Создать',duplicate:'Создать копию'})) {
    add(`${verb} ${entity}`,`${russian} ${forms.object}`);
    if (verb==='select') { add(`select a ${entity}`,`Выберите ${forms.object}`); add(`select a ${entity}...`,`Выберите ${forms.object}…`); }
    if (verb==='create') add(`+ new ${entity}`,`+ Создать ${forms.object}`);
  }
  for (const [status, russian] of Object.entries({created:forms.created,generated:forms.created,updated:forms.updated,deleted:forms.deleted})) {
    add(`${entity} ${status}`,russian); add(`${entity} ${status} successfully`,russian); add(`${entity} ${status} successfully!`,russian);
  }
  add(`no ${entity} selected`,forms.selected); add(`no ${entity} found.`,forms.found);
  const plural=entity==='class'?'classes':entity==='subclass'?'subclasses':entity==='memory'?'memories':entity==='race'?'races':entity==='one-shot'?'one-shots':`${entity}s`;
  add(`search ${plural}...`,`Поиск: ${forms.many}…`); add(`no ${plural} found.`,forms.found);
  add(`loading ${plural}...`,`Загрузка: ${forms.many}…`);
  add(`enter ${entity} name...`,`Введите название ${forms.genitive}…`);
  add(`enter ${entity} title...`,`Введите название ${forms.genitive}…`);
  add(`enter ${entity} description`,`Введите описание ${forms.genitive}`);
  add(`enter the ${entity} description...`,`Введите описание ${forms.genitive}…`);
}
for (const [source,target] of Object.entries({
  'voice':'голос', 'ability':'характеристику', 'alignment':'мировоззрение','character status':'состояние персонажа',
  'pronouns':'местоимения','roll type':'тип броска','stat':'характеристику','type':'тип','damage type':'тип урона',
})) add(`select ${source}`,`Выберите ${target}`);
for (const [source,target] of Object.entries({inventory:'инвентарь',party:'группу',spellbook:'книгу заклинаний'})) {
  add(`add to ${source}`,`Добавить в ${target}`); add(`remove from ${source}`,`Удалить из ${source==='party'?'группы':source==='inventory'?'инвентаря':'книги заклинаний'}`);
}
for (const [source,target] of Object.entries({'left hand':'левую руку','right hand':'правую руку'})) {
  add(`equip ${source}`,`Взять в ${target}`); add(`unequip ${source}`,`Освободить ${source==='left hand'?'левую':'правую'} руку`);
  add(`switch to ${source}`,`Переложить в ${target}`); add(`weapon switched to ${source}`,`Оружие переложено в ${target}`);
}
for (const [source,target] of Object.entries({'item added':'Предмет добавлен','items added':'Предметы добавлены','item dropped':'Предмет выброшен','drop item':'Выбросить предмет','item equipped':'Предмет надет','item unequipped':'Предмет снят','spell added':'Заклинание добавлено','spell added!':'Заклинание добавлено!','spells added':'Заклинания добавлены','faction saved':'Фракция сохранена','faction member added':'Участник добавлен во фракцию','faction member removed':'Участник удалён из фракции','add member':'Добавить участника','add faction member':'Добавить участника фракции','faction name':'Название фракции','faction color':'Цвет фракции','enter faction name':'Введите название фракции','fixed bonus':'Фиксированный бонус','requirements':'Требования'})) add(source,target);
for (const [source,target] of Object.entries({'str - strength':'СИЛ — Сила','dex - dexterity':'ЛОВ — Ловкость','con - constitution':'ТЕЛ — Телосложение','int - intelligence':'ИНТ — Интеллект','wis - wisdom':'МДР — Мудрость','cha - charisma':'ХАР — Харизма'})) add(source,target);

for (const [source,target] of Object.entries({
  "(1 selected)": "(выбран 1)",
  "← back to categories": "← Назад к категориям",
  "← back to stat selection": "← Назад к выбору характеристики",
  "add to context": "Добавить в контекст",
  "archive all blocks?": "Архивировать все блоки?",
  "are you sure you want to delete this block? this action cannot be undone.": "Удалить этот блок? Это действие нельзя отменить.",
  "are you sure you want to delete this message? this action cannot be undone.": "Удалить это сообщение? Это действие нельзя отменить.",
  "area descriptions:": "Описания областей:",
  "asi": "Улучшение характеристик",
  "available quest:": "Доступное задание:",
  "cannot delete start event": "Нельзя удалить начальное событие",
  "choose a page from the sidebar to view its content": "Выберите страницу на боковой панели для просмотра",
  "choose how to proceed": "Выберите продолжение",
  "claim your free daily credits": "Получить бесплатные ежедневные кредиты",
  "click paragraphs and headings to select text": "Нажимайте на абзацы и заголовки для выделения текста",
  "context agent setting updated": "Настройка агента контекста обновлена",
  "context block created": "Блок контекста создан",
  "context block not found": "Блок контекста не найден",
  "context group settings reset to defaults": "Настройки групп контекста сброшены",
  "context group settings saved": "Настройки групп контекста сохранены",
  "create new character": "Создать нового персонажа",
  "delete all blocks?": "Удалить все блоки?",
  "delete block?": "Удалить блок?",
  "delete message?": "Удалить сообщение?",
  "delete messages up to here?": "Удалить сообщения до этого места?",
  "discover more one-shots": "Найти другие короткие приключения",
  "e.g., 3d6+1d8, 2d10+5, 1d20": "Например: 3d6+1d8, 2d10+5, 1d20",
  "e.g., 4d4, 2d6+1d8, 1d20": "Например: 4d4, 2d6+1d8, 1d20",
  "encounter entities updated": "Участники боя обновлены",
  "ending": "Окончание",
  "event deleted": "Событие удалено",
  "events deleted": "События удалены",
  "factions:": "Фракции:",
  "failed to generate enemies for encounter": "Не удалось создать противников для боя",
  "fled": "Сбежал",
  "surrendered": "Сдался",
  "inventory updates undone": "Изменения инвентаря отменены",
  "is no longer": "больше не",
  "is now": "теперь",
  "loading context block...": "Загрузка блока контекста…",
  "message updated": "Сообщение обновлено",
  "monsters added": "Монстры добавлены",
  "movement undone": "Перемещение отменено",
  "moves": "перемещается",
  "multiple entities had their hp modified": "ОЗ нескольких участников изменены",
  "multiple hp changes applied": "Применено несколько изменений ОЗ",
  "multiple monsters had their hp modified": "ОЗ нескольких монстров изменены",
  "new class features!": "Новые умения класса!",
  "new turn order:": "Новый порядок ходов:",
  "new!": "Новое!",
  "no feats found": "Черты не найдены",
  "no world found": "Мир не найден",
  "no location data available. your character must be at a point of interest or inside an area to generate a scene.": "Нет данных о месте. Для создания сцены персонаж должен находиться в интересном месте или внутри области.",
  "no narrative found for this campaign. plot content will appear here once available.": "Повествование кампании пока отсутствует. Сюжет появится здесь, когда будет доступен.",
  "one shot completed!": "Короткое приключение завершено!",
  "open memory dropdown menu": "Открыть меню воспоминания",
  "plot summary help information": "Справка по краткому изложению сюжета",
  "plot updated successfully": "Сюжет обновлён",
  "previous:": "Прежнее значение:",
  "saved": "Сохранено",
  "scene generated successfully!": "Сцена создана!",
  "select a character to reincarnate as or create a new one.": "Выберите персонажа для нового воплощения или создайте нового.",
  "starts at": "Начинается с",
  "suggestions unavailable": "Подсказки недоступны",
  "tap paragraphs and headings to select text": "Нажимайте на абзацы и заголовки для выделения текста",
  "these characters are at the poi, but distant.": "Эти персонажи находятся в этом месте, но далеко от вас.",
  "these characters are closest to you and highly relevant.": "Эти персонажи находятся ближе всего к вам и важны для текущей сцены.",
  "these characters are present but further away.": "Эти персонажи присутствуют, но находятся дальше.",
  "this may take up to a minute...": "Это может занять до минуты…",
  "tip: if you don't like the direction franz is going in, you can regenerate the message using the button to the right, or you can edit his response by clicking the 3 dots.": "Совет: если вам не нравится направление повествования Франца, создайте сообщение заново кнопкой справа или отредактируйте ответ через меню с тремя точками.",
  "tip: you can click any of the avatars at the top of the page to quickly view your party's character sheets.": "Совет: нажмите на аватар вверху страницы, чтобы открыть лист персонажа группы.",
  "you're running out of credits! (10 left)": "Кредиты заканчиваются! Осталось 10.",
  "you've reached your max working context character limit. upgrade for higher working context limits.": "Достигнут лимит символов рабочего контекста. Улучшите подписку, чтобы увеличить его.",
  "what next?": "Что дальше?",
  "you have successfully completed this quest": "Вы завершили это задание",
  "try adjusting your search or filter criteria": "Измените поисковый запрос или фильтры",
  "undo all inventory updates?": "Отменить все изменения инвентаря?",
  "undo entire transaction?": "Отменить все изменения?",
  "upgrade your plan.": "Улучшите подписку.",
  "transaction completed!": "Изменения применены!",
  "toggle truncation": "Показать или свернуть полный текст",
  "↵ enter": "↵ Enter",
  "are you sure you want to delete this encounter note? this action cannot be undone.": "Удалить эту заметку боя? Это действие нельзя отменить.",
  "are you sure you want to end this encounter? this will immediately end the encounter without rewards and cannot be undone.": "Завершить бой? Он закончится немедленно, без наград. Это действие нельзя отменить.",
  "campaign restored": "Кампания восстановлена",
  "campaign saved": "Кампания сохранена",
  "cancel quest?": "Отменить задание?",
  "character added": "Персонаж добавлен",
  "delete encounter note": "Удалить заметку боя",
  "encounter ended": "Бой завершён",
  "last encounter id:": "ID последнего боя:",
  "last event id:": "ID последнего события:",
  "loading notes...": "Загрузка заметок…",
  "location data not available": "Сведения о месте отсутствуют",
  "max level reached": "Достигнут максимальный уровень",
  "note deleted": "Заметка удалена",
  "note updated": "Заметка обновлена",
  "quest canceled": "Задание отменено",
  "quest completed!": "Задание завершено!",
  "quest step completed": "Этап задания завершён",
  "removed on save:": "Удаляется при сохранении:",
  "select new location": "Выберите новое место",
  "change quantity": "Изменить количество",
  "change type": "Изменить тип",
  "character not found": "Персонаж не найден",
  "choose a character to add to this faction. you can search by name or scroll through the list.": "Выберите персонажа для добавления во фракцию. Найдите его по имени или в списке.",
  "choose a character to establish a relationship with. you can search by name or scroll through the list.": "Выберите персонажа для установления отношений. Найдите его по имени или в списке.",
  "duplicate": "Создать копию",
  "e.g., after long rest, when concentration ends": "Например: после продолжительного отдыха, после окончания концентрации",
  "e.g., blessing of strength, magic item, curse": "Например: благословение Силы, магический предмет, проклятие",
  "equipped": "Надето",
  "favorited": "В избранном",
  "featured": "Рекомендуемое",
  "inventory is not available in the workshop. add this character to a world first.": "Инвентарь недоступен в мастерской. Сначала добавьте персонажа в мир.",
  "search character names...": "Поиск по имени персонажа…",
  "search members...": "Поиск участников…",
  "select a voice": "Выберите голос",
  "special resistances and immunities your character has. immunities negate damage/conditions, resistances halve damage, and vulnerabilities double damage taken.": "Особые сопротивления и иммунитеты персонажа. Иммунитеты исключают урон или состояния, сопротивления уменьшают урон вдвое, а уязвимости удваивают его.",
  "this relationship graph is view-only. use the list view to make changes.": "Граф отношений доступен только для просмотра. Изменяйте отношения в режиме списка.",
  "unable to add some items as an item with that name already exists in the campaign.": "Некоторые предметы не добавлены: предметы с такими именами уже есть в кампании.",
  "unable to add some items as an item with that name already exists in the world.": "Некоторые предметы не добавлены: предметы с такими именами уже есть в мире.",
  "edit the original monster from their full sheet to update their ac.": "Измените КБ исходного монстра в его полном листе.",
  "edit the original monster from their full sheet to update their speed.": "Измените скорость исходного монстра в его полном листе.",
  "view full sheet": "Открыть полный лист",
  "add npc": "Добавить НИП",
  "player removed": "Игрок исключён",
  "remove entity?": "Удалить объект?",
  "memory added to working context": "Воспоминание добавлено в рабочий контекст",
  "delete this memory?": "Удалить это воспоминание?",
  "confirm move": "Подтвердить перемещение",
  "are you sure you want to move this entity?": "Переместить этот объект?",
  "is this entity friendly to the party?": "Этот объект дружелюбен к группе?",
  "step marked as incomplete": "Этап отмечен как незавершённый",
  "sync characters?": "Синхронизировать персонажей?",
  "sync lore pages?": "Синхронизировать страницы сведений о мире?",
  "new characters": "Новые персонажи",
  "updated characters": "Обновлённые персонажи",
  "updated pages": "Обновлённые страницы",
  "character selected": "Персонаж выбран",
  "character exported to workshop": "Персонаж опубликован в мастерской",
  "character image": "Изображение персонажа",
  "one shot briefing not found.": "Вводные сведения короткого приключения не найдены.",
  "when enabled, existing characters with matching names will be overwritten with the updates from the world.": "Если включено, персонажи с совпадающими именами будут перезаписаны обновлениями из мира."
})) add(source,target);

// Search/loading hints use plural genitives; character names are personal names.
for (const [source,target] of Object.entries({characters:'персонажей',items:'предметов',spells:'заклинаний',feats:'черт',classes:'классов',subclasses:'подклассов',races:'рас',factions:'фракций',locations:'мест',monsters:'монстров',quests:'заданий','quest steps':'этапов задания',paths:'путей',relationships:'отношений',memories:'воспоминаний','one-shots':'коротких приключений'})) {
  for (const [verb,russian] of Object.entries({search:'Поиск',loading:'Загрузка'})) {
    const key=`${verb} ${source}...`;
    if (SHARED_INTERFACE_GLOSSARY[key]?.includes(':')) SHARED_INTERFACE_GLOSSARY[key]=`${russian} ${target}…`;
  }
}
SHARED_INTERFACE_GLOSSARY['enter character name...']='Введите имя персонажа…';
